"use client";

import React, { useRef } from 'react';
import Image from 'next/image';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/dist/ScrollTrigger';
import { DrawSVGPlugin } from 'gsap/dist/DrawSVGPlugin';
import { useGSAP } from '@gsap/react';

if (typeof window !== 'undefined') {
  gsap.registerPlugin(ScrollTrigger, DrawSVGPlugin, useGSAP);
  ScrollTrigger.clearScrollMemory("manual");
  window.history.scrollRestoration = "manual";
  // Attempt to reset scroll before React even mounts
  window.scrollTo(0, 0);
  window.addEventListener('beforeunload', () => {
    window.scrollTo(0, 0);
  });
}

/* ═══════════════════════════════════════════════════════════════════
 * AboutOpening — cinematic opener for /hakkimizda.
 *
 * Two coupled acts, both driven from this one component:
 *
 *   Act 1 (timed, scroll locked) — black curtain lifts on a greyscale
 *     olive grove, the emblem's outline is drawn stroke by stroke, the
 *     filled logo cross-fades in over it, colour returns, scroll opens.
 *
 *   Act 2 (scrubbed) — the scene is pinned with CSS sticky while the
 *     window frame closes in around the grove and the taster rises into
 *     the room, the view behind her falling out of focus.
 *
 * The emblem outline comes from public/assets/opening-logo-ink.svg,
 * generated by scripts/extract-logo-ink.mjs. It covers the emblem only
 * (the auto-traced source has no wordmark), so it is positioned inside
 * the logo box at INK_BOX — the rectangle the emblem occupies within
 * opening-logo.png's 1407×768 frame.
 * ═══════════════════════════════════════════════════════════════════ */

/** Emblem rectangle within opening-logo.png, measured from its alpha bounds. */
const INK_BOX = {
  left: '26.80%',
  top: '3.40%',
  width: '46.95%',
  height: '67.24%',
} as const;

interface AboutOpeningProps {
  /** Inner markup of opening-logo-ink.svg, read at build time by the page. */
  inkPaths: string;
}

export default function AboutOpening({ inkPaths }: AboutOpeningProps) {
  const sectionRef = useRef<HTMLElement>(null);
  const colorRef = useRef<HTMLDivElement>(null);
  const bgRef = useRef<HTMLDivElement>(null);
  const windowRef = useRef<HTMLDivElement>(null);
  const womenRef = useRef<HTMLDivElement>(null);
  const logoRef = useRef<HTMLDivElement>(null);
  const inkRef = useRef<SVGSVGElement>(null);
  const logoPngRef = useRef<HTMLDivElement>(null);
  const curtainRef = useRef<HTMLDivElement>(null);
  const cueRef = useRef<HTMLDivElement>(null);

  useGSAP(() => {
    // Prevent browser from restoring scroll position on reload, which breaks the opening sequence.
    let prevRestore: ScrollRestoration | null = null;
    if (typeof history !== 'undefined' && history.scrollRestoration) {
      prevRestore = history.scrollRestoration;
      history.scrollRestoration = 'manual';
    }

    // Force scroll to top immediately before GSAP reads any layout
    window.scrollTo(0, 0);
    document.documentElement.scrollTop = 0;
    document.body.scrollTop = 0;

    const mm = gsap.matchMedia();

    /* ── Act 2: scrubbed scene ───────────────────────────────────── */
    const scene = gsap.timeline({
      scrollTrigger: {
        trigger: sectionRef.current,
        start: 'top top',
        end: 'bottom bottom',
        scrub: 0.8,
      },
    });

    scene
      // The grove drifts in a touch so the frame never uncovers an edge.
      .fromTo(bgRef.current,
        { scale: 1 },
        { scale: 1.06, ease: 'none', duration: 0.5 }, 0)
      // The window closes in from oversized — this is what reads as "pulling back".
      .fromTo(windowRef.current,
        { scale: 1.35 },
        { scale: 1, ease: 'none', duration: 0.45 }, 0)
      // Eased in so the two scenes spend as little time as possible half-dissolved.
      .fromTo(windowRef.current,
        { autoAlpha: 0 },
        { autoAlpha: 1, ease: 'power2.in', duration: 0.45 }, 0)
      // Drop the grove once the window covers it, so the dissolve resolves cleanly.
      .to(bgRef.current,
        { autoAlpha: 0, ease: 'none', duration: 0.2 }, 0.25)
      // The cue belongs to the held frame only.
      .to(cueRef.current,
        { autoAlpha: 0, ease: 'none', duration: 0.08 }, 0)
      .fromTo(logoRef.current,
        { scale: 1, yPercent: 0 },
        { scale: 0.52, yPercent: -6, ease: 'none', duration: 0.6 }, 0.1)
      .fromTo(womenRef.current,
        { autoAlpha: 0, yPercent: 14 },
        { autoAlpha: 1, yPercent: 0, ease: 'none', duration: 0.45 }, 0.45)
      // Depth of field: the view behind her softens as she takes the frame.
      .fromTo(windowRef.current,
        { filter: 'blur(0px)' },
        { filter: 'blur(7px)', ease: 'none', duration: 0.45 }, 0.45)
      .to(logoRef.current,
        { autoAlpha: 0, ease: 'none', duration: 0.45 }, 0);

    /* ── Act 1: timed intro ──────────────────────────────────────── */
    const inkStrokes = inkRef.current
      ? gsap.utils.toArray<SVGPathElement>(inkRef.current.querySelectorAll('path'))
      : [];

    const restEnd = () => {
      gsap.set(curtainRef.current, { autoAlpha: 0 });
      gsap.set(colorRef.current, { filter: 'grayscale(0) brightness(1)' });
      gsap.set(inkRef.current, { autoAlpha: 0 });
      gsap.set(logoPngRef.current, { autoAlpha: 1 });
      gsap.set(cueRef.current, { autoAlpha: 1 });
    };

    mm.add('(prefers-reduced-motion: reduce)', () => {
      restEnd();
    });

    mm.add('(prefers-reduced-motion: no-preference)', () => {
      // Hold the reader at the top until the emblem has been drawn.
      const scrollbar = window.innerWidth - document.documentElement.clientWidth;
      document.body.style.overflow = 'hidden';
      if (scrollbar > 0) document.body.style.paddingRight = `${scrollbar}px`;

      const unlock = () => {
        document.body.style.overflow = '';
        document.body.style.paddingRight = '';
        ScrollTrigger.refresh();
      };

      gsap.set(inkStrokes, { drawSVG: 0 });

      const intro = gsap.timeline();
      intro
        .to(curtainRef.current, { autoAlpha: 0, duration: 0.9, ease: 'power2.out' }, 0.3)
        .to(colorRef.current, { filter: 'grayscale(1) brightness(1)', duration: 1.4, ease: 'power2.out' }, 0.3)
        .set(inkRef.current, { autoAlpha: 1 }, 1.0)
        .to(inkStrokes, {
          drawSVG: '100%',
          duration: 1.5,
          ease: 'none',
          stagger: { amount: 1.0 },
        }, 1.0)
        .to(logoPngRef.current, { autoAlpha: 1, duration: 0.8, ease: 'power1.inOut' }, 3.4)
        .to(inkRef.current, { autoAlpha: 0, duration: 0.6, ease: 'power1.inOut' }, 3.5)
        .to(colorRef.current, { filter: 'grayscale(0) brightness(1)', duration: 1.2, ease: 'power2.inOut' }, 3.9)
        .call(unlock, undefined, 5.0)
        .to(cueRef.current, { autoAlpha: 1, duration: 0.6 }, 5.0);

      return () => {
        unlock();
      };
    });

    return () => {
      scene.scrollTrigger?.kill();
      mm.revert();
      if (prevRestore !== null && typeof history !== 'undefined') {
        history.scrollRestoration = prevRestore;
      }
    };
  }, { scope: sectionRef });

  return (
    <section ref={sectionRef} className="relative h-[320vh] bg-black">
      {/* Sticky pin — no ScrollTrigger pin-spacer needed. */}
      <div className="sticky top-0 h-screen w-full overflow-hidden">

        {/* Everything that desaturates together during the intro. */}
        <div
          ref={colorRef}
          className="absolute inset-0"
          style={{ filter: 'grayscale(1) brightness(0.25)' }}
        >
          {/* 1. Olive grove */}
          <div ref={bgRef} className="absolute inset-0 will-change-transform">
            <Image
              src="/assets/opening-bg.webp"
              alt="Yüzyıllık zeytin bahçelerimiz"
              fill
              className="object-cover"
              sizes="100vw"
              priority
            />
          </div>

          {/* 2. The room's window, oversized until the scene pulls back */}
          <div ref={windowRef} className="absolute inset-0 will-change-transform opacity-0">
            <Image
              src="/assets/opening-window.webp"
              alt=""
              fill
              className="object-cover"
              sizes="100vw"
              aria-hidden="true"
            />
          </div>

          {/* 3. The taster. Painted on white paper — multiply drops the paper. */}
          <div
            ref={womenRef}
            className="absolute inset-0 opacity-0 mix-blend-multiply will-change-transform"
          >
            <Image
              src="/assets/opening-man.webp"
              alt="Zeytinyağı numunelerini inceleyen ustamız"
              fill
              className="object-contain object-bottom origin-bottom scale-[1.55] sm:scale-[1.12]"
              sizes="100vw"
            />
          </div>

          {/* 4. Emblem — outline drawn first, filled logo cross-faded over it */}
          <div ref={logoRef} className="absolute inset-0 grid place-items-center will-change-transform">
            <div className="relative w-[88vw] sm:w-[78vw] max-w-[900px] min-w-[300px]" style={{ aspectRatio: '1407 / 768' }}>
              {/* Paper halo — the grove is busy behind the emblem; this keeps the
                  ink legible without flattening the illustration. */}
              <div
                className="absolute -inset-[18%] pointer-events-none"
                aria-hidden="true"
                style={{
                  background:
                    'radial-gradient(ellipse at center, rgba(250,250,245,0.80) 0%, rgba(250,250,245,0.44) 38%, rgba(250,250,245,0.12) 58%, rgba(250,250,245,0) 74%)',
                }}
              />
              {/* non-scaling-stroke keeps the line a hairline at any logo size */}
              <svg
                ref={inkRef}
                viewBox="0 0 655 512"
                aria-hidden="true"
                className="absolute text-[#26221c] opacity-0 [&_path]:[vector-effect:non-scaling-stroke] [&_path]:[stroke-width:1.1px] drop-shadow-[0_1px_3px_rgba(255,255,255,0.5)]"
                style={INK_BOX}
                dangerouslySetInnerHTML={{ __html: inkPaths }}
              />
              <div ref={logoPngRef} className="absolute inset-0 opacity-0">
                <Image
                  src="/assets/opening-logo.png"
                  alt="Bu Başka Lezzet"
                  fill
                  className="object-contain drop-shadow-[0_6px_24px_rgba(0,0,0,0.35)]"
                  sizes="(max-width: 640px) 88vw, 900px"
                />
              </div>
            </div>
          </div>
        </div>

        {/* Intro curtain — below the layout's white frame (z-9999) by design. */}
        <div ref={curtainRef} className="absolute inset-0 z-40 bg-black pointer-events-none" />

        {/* Scroll cue */}
        <div
          ref={cueRef}
          className="absolute inset-x-0 bottom-10 md:bottom-14 z-30 flex flex-col items-center gap-3 opacity-0 pointer-events-none"
        >
          <svg
            width="22" height="34" viewBox="0 0 22 34" fill="none" aria-hidden="true"
            className="text-stone-800 drop-shadow-[0_1px_4px_rgba(250,250,245,0.9)]"
          >
            <rect x="1" y="1" width="20" height="32" rx="10" stroke="currentColor" strokeWidth="1.5" opacity="0.85" />
            <rect x="10" y="8" width="2" height="6" rx="1" fill="currentColor" opacity="0.85" />
          </svg>
          <p className="font-serif italic text-sm md:text-base text-stone-800 tracking-wide drop-shadow-[0_1px_4px_rgba(250,250,245,0.95)]">
            Hikâyemiz için kaydırın
          </p>
        </div>

      </div>
    </section>
  );
}
